on:
  push:
    branches:
      - "**"

jobs:
  web_lint:
    runs-on: ubuntu-latest
    needs: api_build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: |
          cd web-client
          yarn install --no-lockfile
          yarn lint

  api_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - run: |
          cd vote-api
          go mod tidy
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ./bin v1.63.1
          ./bin/golangci-lint run

  api_tests:
    runs-on: ubuntu-latest
    needs: api_lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - run: |
          cd vote-api
          go test ./...

  api_build:
    runs-on: ubuntu-latest
    needs: api_tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - run: |
          cd vote-api
          go build

  web_build:
    runs-on: ubuntu-latest
    needs: web_lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: |
          cd web-client
          yarn install --no-lockfile
          yarn build

  format_front:
    runs-on: ubuntu-latest
    needs: web_build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: |
          cd web-client
          yarn install --no-lockfile
          yarn format:check

  web_tests:
    runs-on: ubuntu-latest
    needs: web_build
    steps:
      - uses: actions/checkout@v4
      - name: Start containers
        run: docker compose -f "docker-compose.yaml" up -d --build
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: |
          cd web-client
          yarn install
          yarn playwright install
          yarn test
          yarn e2e

  format_back:
    runs-on: ubuntu-latest
    needs: api_build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - run: |
          cd vote-api
          go fmt ./...

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: |
          cd docs
          yarn install --no-lockfile
          yarn build

  push_api_to_registry:
    name: push docker image to hub
    needs: api_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.THEMIS_DOCKER_USERNAME}}
          password: ${{secrets.THEMIS_DOCKER_PASSWORD}}
      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: ./vote-api
          push: true
          tags: charlierthemis/vote-api:latest

  push_web_to_registry:
    name: push docker image to hub
    needs: web_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.ADRIEN_DOCKER_USERNAME}}
          password: ${{secrets.ADRIEN_DOCKER_PASSWORD}}
      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: ./web-client
          push: true
          tags: adriendegand/web-client:latest
