on:
  push:
    branches:
      - "*"

jobs:
  api_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - run: |
          cd vote-api
          go test ./...

  api_build:
    runs-on: ubuntu-latest
    needs: api_tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: "1.23"

      - run: |
          cd vote-api
          go build

  web_tests:
    runs-on: ubuntu-latest
    needs: api_build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"

      - run: |
          cd web-client
          yarn test
          yarn e2e

  web_build:
    runs-on: ubuntu-latest
    needs: web_tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"

      - run: |
          cd web-client
          yarn build

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "yarn"

      - run: |
          cd doc
          yarn build

  push_api_to_registry:
    name: push docker image to hub
    needs: api_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.THEMIS_DOCKER_USERNAME}}
          password: ${{secrets.THEMIS_DOCKER_PASSWORD}}
      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: ./vote-api
          push: true
          tags: charlierthemis/vote-api:latest

  push_web_to_registry:
    name: push docker image to hub
    needs: web_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.ADRIEN_DOCKER_USERNAME}}
          password: ${{secrets.ADRIEN_DOCKER_PASSWORD}}
      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: ./web-client
          push: true
          tags: adriendegand/web-client:latest
